apiVersion: v1
kind: Pods
metadata: 
  name: pioneer-samplepod
  lables:
    name: myapp
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      ports: 
        - containerPort: 80
