apiVersion: v1
kind: Pods
metadata:
  name: postgres
  lables:
    tier: db-tier
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_USERNAME
          value: admin
        - name: POSTGRES_PASSWORD
          value: mysecretpassword

