apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: db-tier
spec:
  containers:
    - name: postgres
      image: postgres
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: POSTGRES_USERNAME
          value: admin
        - name: POSTGRES_PASSWORD
          value: mysecretpassword

